modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"
logoFile = "assets/pas/icon.png"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Danrus1100/PlayerArmorStand"
description = '''${mod_description}'''
authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3,]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[9,]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_versions}"